name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [21]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'

      - name: Build
        run: mvn -B package --file pom.xml